### ISSUE TITLE
Add some common clients to airflow worker image

### ISSUE THREAD

**Issue by tinylambda** [bitnami/bitnami-docker-airflow-worker#22]
### Name and Version

bitnami/bitnami-docker-airflow-worker

### What is the problem this feature will solve?

airflow's BashOperator can execute script use the OS's supplied commands.

we have some scripts that use mysql redis ... comands to get something done.

but this airflow worker image   has no mysql command  redis command ...

### What is the feature you are proposing to solve the problem?

What about installing some common package when build image, mysql-client redis-client ..

### What alternatives have you considered?

we can ship the client commands with the airflow task, use them to complete our work. that's heavy.

**Comment by fmulero** [comment]
Hi @tinylambda 

Thanks for using our images. In our developments we follow some common principles, widely used by the community, like Single Responsability or Self-containemt principle. What does it mean? A container should do what is supposed to do and only that, and all its dependencies and only those are resolved in order to achieve the purpose of the container. I know this case is very particular because airflow worker can execute other tasks, but we can not infer at build time any particular case. You can always fork this project and/or extend this image with your concrete requirements

Regards
